language: php
php:
- '7.0'
- '7.1'
- '7.2'
before_script:
- composer self-update
- composer global require "fxp/composer-asset-plugin:~1.0.0"
- composer install --prefer-source --no-interaction
script: phpunit
